### ISSUE TITLE
SolarNetwork Developer Virtual Machine Guide 

### ISSUE THREAD

**Issue by rmanicav** [SolarNetwork/solarnetwork-central#5] opened 2021-03-08 18:01 UTC
This is not an issue. I am just getting lots of unresolved errors. I followed all the steps mentioned in the guide for solarnetwork Developer Virtual Machine guide.. Even after project - clean. The unresolved errors still exists..  I tried to manually add target platform osgi from install new software. The problem still exists. This might be a simple settings change. 

Please see attachment for the screenshot
![Unresolved](https://user-images.githubusercontent.com/44268387/110361483-14b16680-800e-11eb-81f9-1eb85580f3eb.PNG)

Thank you for your support.

**Comment by msqr** [comment] 2021-03-08 19:10
By "Developer Virtual Machine" are you referring to the Vagrant [Development VM](https://github.com/SolarNetwork/solarnetwork-dev/tree/master/vagrant/solarnet-dev)? That might have fallen out of sync with the central code base and need updating. Or if you're just setting up Eclipse yourself, can you provide some examples of the errors Eclipse is reporting in your workspace?

**Comment by rmanicav** [comment] 2021-03-08 19:48
You are correct. I used vagrant to install the VM. 
1) First error i got was osgi-target not found when i run the solarnetwork. So i added it from install new software. I also added equinox.console to fix another build error.

Attached screen shots shows some errors

![errorjava](https://user-images.githubusercontent.com/44268387/110373216-40881880-801d-11eb-8ed9-f070cbb34284.PNG)
 marker errors. 
![Error](https://user-images.githubusercontent.com/44268387/110373071-0fa7e380-801d-11eb-89d5-6de1d81755aa.PNG)

Thank you for replay.

**Comment by msqr** [comment] 2021-03-08 20:22
I will try to reproduce the problem by setting up a new VM from scratch and report back what I find.

**Comment by rmanicav** [comment] 2021-03-08 21:42
Thank u so much for your response.

**Comment by msqr** [comment] 2021-03-09 00:28
OK I found the problem, in that Git LFS was not being correctly configured in the solarnetwork-build repository. I've fixed that and verified I can follow the setup guide completely. Can you please pull the latest from [SolarNetwork/solarnetwork-dev](https://github.com/SolarNetwork/solarnetwork-dev) and then start over setting up the Vagrant VM? You'll need to `vagrant destroy` your current VM, followed by `vagrant up`.

If you run into issues, please create a new issue in the [solarnetwork-dev](https://github.com/SolarNetwork/solarnetwork-dev/issues) repo, as that is where the Vagrant setup lives.

**Comment by rmanicav** [comment] 2021-03-09 01:03
Hi Matt,

I will pull the latest and will let you know of any issue. Thank you for
your support.

**Comment by msqr** [comment] 2021-03-09 04:31
I've also pushed an update to the [develop](https://github.com/SolarNetwork/solarnetwork-dev/tree/develop) branch that updates the VM to Ubuntu 20.04 LTS. I haven't tested that much, but you could give it a try if you like. Note I discovered an additional step you need to perform: [update Eclipse to use Java 8 by default](https://github.com/SolarNetwork/solarnetwork/wiki/Developer-VM#eclipse-java-setup).

**Comment by rmanicav** [comment] 2021-03-09 14:11
Sure I will do that version and will let you know. Thank you for your
support.

**Comment by rmanicav** [comment] 2021-03-09 15:18
Hi Matt,

Most of the issues have been resolved. Below are pending issues

[image: image.png]

**Comment by msqr** [comment] 2021-03-09 20:54
Looks like your image didn't come through.

**Comment by rmanicav** [comment] 2021-03-09 22:53
Hi Matt,

I apologize for the delay in response. The issue is with just 2 bundles.
datum.app and datum.app.test.
[image: image.png]

[image: image.png]

Thank you,
Rajesh

**Comment by msqr** [comment] 2021-03-09 23:14
For some reason your images are not coming through... however, you might try doing a **Project > Clean... > Clean all projects** as sometimes Eclipse get a little hung up on itself.

**Comment by rmanicav** [comment] 2021-03-09 23:45
Hi Matt,

I tried Project clean several times. Its the same issue with 2 bundles. I
am attaching images as attachments.

Thank you,
Rajesh

**Comment by msqr** [comment] 2021-03-10 00:01
Hmm, still your images do not show up; check out https://github.com/SolarNetwork/solarnetwork-central/issues/5 and maybe you can add the image(s) there. You could also copy/paste the error message(s).

**Comment by rmanicav** [comment] 2021-03-10 00:08
Hi Matt,

Please see attached images.
![bundle](https://user-images.githubusercontent.com/44268387/110555532-bcac5a00-810a-11eb-959f-a649af785590.PNG)
![bundle1](https://user-images.githubusercontent.com/44268387/110555533-bd44f080-810a-11eb-8f38-a14a58c35de9.PNG)

Thank you

**Comment by msqr** [comment] 2021-03-10 01:20
Unfortunately I can't really tell much from the screen shots. I just recreated the VM from scratch and indeed after loading the projects the first time the `n.s.c.datum.aop` project has the same error as you show, but after selecting **Project > Clean... > Clean all projects** once it fixed all errors. Can you confirm you [changed the default JRE](https://github.com/SolarNetwork/solarnetwork/wiki/Developer-VM#eclipse-java-setup) to `/usr/lib/jvm/java-8-openjdk-amd64`? Here's what my project looked like with the error, and the JRE expanded:
![datum_aop-build-error](https://user-images.githubusercontent.com/139448/110560952-bc17d000-81ab-11eb-8f9b-bf9a882c2945.png)

**Comment by rmanicav** [comment] 2021-03-10 01:24
Hi Matt,
I did not change default jre. I will change it and will let you know.
Thanks again for your help.

**Comment by msqr** [comment] 2021-03-11 20:09
Hey @rmanicav did you have any luck?

**Comment by rmanicav** [comment] 2021-03-11 20:45
Hey matt,

I will try again and let you know.

**Comment by rmanicav** [comment] 2021-03-12 16:44
Hi Matt,

There are some errors in different bundles. I am able to open a
solarnetwork website from localhost. I will try to uninstall and redo the
whole process and will let you know.

Thank you so much for your support.

**Comment by msqr** [comment] 2021-03-16 19:42
Thanks @rmanicav. It sounds like I can close this ticket now.

**Closed as completed by msqr** 2021-03-16 19:42 UTC

**Comment by rmanicav** [comment] 2021-03-16 20:53
Hi Matt,

When i register as new user, i dont get confirmation email to confirm my
account.

Thank you for support

**Comment by msqr** [comment] 2021-03-16 23:21
The development environment does not send actual emails. Read carefully [the guide](https://github.com/SolarNetwork/solarnetwork/wiki/Developer-VM#create-a-development-solarnet-account): you have to extract the confirmation URL out of the console log:

> The development environment is set up to simply log outbound email messages, so look in the Eclipse console and you should see the confirmation URL there. Is will take the form of
> 
> http://localhost:8080/solaruser/register/confirm.do?...
> 
> Copy that entire URL, and paste it into the browser to visit it. That will complete the registration process, and you should then log in.

**Comment by rmanicav** [comment] 2021-03-17 18:28
Hi Matt,

It worked after copying the URL from the console. Thank you so much for
your support and patience. The issue can be closed.

**Comment by msqr** [comment] 2021-03-17 20:29
Glad to hear that!
